// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtO7eN0pJz-LkoCbMwQpiIcG7SI9iEb8w',
    appId: '1:670497527692:web:ccd51a19cb02176744e8a9',
    messagingSenderId: '670497527692',
    projectId: 'instagram-flutter-hvp180822',
    authDomain: 'instagram-flutter-hvp180822.firebaseapp.com',
    storageBucket: 'instagram-flutter-hvp180822.appspot.com',
    measurementId: 'G-Y1JKD8QQ71',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBoPy_RS9c9qeFCXPA_pFEFsY5DA0kSrg',
    appId: '1:670497527692:android:0f6495819e04a9f044e8a9',
    messagingSenderId: '670497527692',
    projectId: 'instagram-flutter-hvp180822',
    storageBucket: 'instagram-flutter-hvp180822.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDybEHho65pxz2RnY2NSxlLkOR9Mz5FIPU',
    appId: '1:670497527692:ios:1ea4b3870308c9fa44e8a9',
    messagingSenderId: '670497527692',
    projectId: 'instagram-flutter-hvp180822',
    storageBucket: 'instagram-flutter-hvp180822.appspot.com',
    iosClientId: '670497527692-5cth9aeefde1eosvmjjb0tnq8inhvfkm.apps.googleusercontent.com',
    iosBundleId: 'com.example.instagramFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDybEHho65pxz2RnY2NSxlLkOR9Mz5FIPU',
    appId: '1:670497527692:ios:1ea4b3870308c9fa44e8a9',
    messagingSenderId: '670497527692',
    projectId: 'instagram-flutter-hvp180822',
    storageBucket: 'instagram-flutter-hvp180822.appspot.com',
    iosClientId: '670497527692-5cth9aeefde1eosvmjjb0tnq8inhvfkm.apps.googleusercontent.com',
    iosBundleId: 'com.example.instagramFlutter',
  );
}
